// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEJtoSLWQRXSV3r03sjAzKRGlbMA8qbHI',
    appId: '1:174614038160:web:f3d6d9df15b778383a3a15',
    messagingSenderId: '174614038160',
    projectId: 'fir-setup-807d3',
    authDomain: 'fir-setup-807d3.firebaseapp.com',
    storageBucket: 'fir-setup-807d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa1FtpjoUATNSsspliK-AVSSaUwV4exh8',
    appId: '1:174614038160:android:6e5f30682a22e16d3a3a15',
    messagingSenderId: '174614038160',
    projectId: 'fir-setup-807d3',
    storageBucket: 'fir-setup-807d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE1qkYXWbYexI8EBzI4vC5huZ2yLRAGZ8',
    appId: '1:174614038160:ios:8e21f7f1a8def70c3a3a15',
    messagingSenderId: '174614038160',
    projectId: 'fir-setup-807d3',
    storageBucket: 'fir-setup-807d3.appspot.com',
    iosBundleId: 'com.example.firebaseauthnew',
  );
}
